
(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#mainCanvas'), ctx=canvas.getContext('2d',{willReadFrequently:true}), wrap=$('#canvasWrap');
const state={mode:'crop',sources:[],source:null,view:{scale:1,x:0,y:0},tool:'rect',selection:null,poly:[],free:[],drawing:false,detected:[],assets:[],layers:[],selectedLayer:null,recipes:{},dish:{w:768,h:768,bg:'checker'},dragLayer:null,projectVersion:1};
const builtins=[['croquette_parts.png','コロッケ本体・皿・焦げ等'],['fillings.png','液体・具材'],['specials.png','足・DJグッズ・演出']];
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1600)}
function status(t){$('#status').textContent=t}
function resize(){const r=wrap.getBoundingClientRect();canvas.width=Math.max(1,Math.floor(r.width*devicePixelRatio));canvas.height=Math.max(1,Math.floor(r.height*devicePixelRatio));draw()}
addEventListener('resize',resize);
function imgFrom(url){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=url})}
async function init(){
  for(const [f,name] of builtins){
    const img=await imgFrom('assets/'+f);
    const src={id:'src_'+crypto.randomUUID(),name,file:f,img,url:'assets/'+f};
    state.sources.push(src);
    await autoExtractBuiltinAssets(src, f.replace(/\.png$/,''));
  }
  state.source=state.sources[0];
  renderSources(); renderAssets(); renderLayers(); renderRecipes();
  resize(); setMode('compose');
  status('内蔵素材を自動分割しました。必要な素材をクリックして合成できます');
}
async function autoExtractBuiltinAssets(src,prefix){
  const im=src.img, c=document.createElement('canvas'); c.width=im.naturalWidth; c.height=im.naturalHeight;
  const g=c.getContext('2d',{willReadFrequently:true}); g.drawImage(im,0,0);
  const dat=g.getImageData(0,0,c.width,c.height).data, W=c.width,H=c.height, ds=3, w=Math.ceil(W/ds), h=Math.ceil(H/ds), thr=18;
  const mask=new Uint8Array(w*h);
  for(let yy=0;yy<h;yy++)for(let xx=0;xx<w;xx++){
    let a=0; for(let sy=0;sy<ds;sy++)for(let sx=0;sx<ds;sx++){
      const x=Math.min(W-1,xx*ds+sx),y=Math.min(H-1,yy*ds+sy); a=Math.max(a,dat[(y*W+x)*4+3]);
    }
    if(a>thr) mask[yy*w+xx]=1;
  }
  const seen=new Uint8Array(w*h), comps=[], qx=new Int32Array(w*h), qy=new Int32Array(w*h);
  for(let yy=0;yy<h;yy++)for(let xx=0;xx<w;xx++){
    let idx=yy*w+xx; if(!mask[idx]||seen[idx]) continue;
    let qs=0,qe=0; qx[qe]=xx; qy[qe++]=yy; seen[idx]=1;
    let minx=xx,maxx=xx,miny=yy,maxy=yy,count=0;
    while(qs<qe){const x=qx[qs],y=qy[qs++]; count++; minx=Math.min(minx,x);maxx=Math.max(maxx,x);miny=Math.min(miny,y);maxy=Math.max(maxy,y);
      for(const [nx,ny] of [[x+1,y],[x-1,y],[x,y+1],[x,y-1]]){if(nx<0||ny<0||nx>=w||ny>=h)continue;const ni=ny*w+nx;if(mask[ni]&&!seen[ni]){seen[ni]=1;qx[qe]=nx;qy[qe++]=ny}}
    }
    if(count>55) comps.push({x:minx*ds,y:miny*ds,w:(maxx-minx+1)*ds,h:(maxy-miny+1)*ds,count});
  }
  comps.sort((a,b)=>a.y-b.y || a.x-b.x);
  let n=1;
  for(const b of comps){
    const pad=8, x=Math.max(0,b.x-pad), y=Math.max(0,b.y-pad), rw=Math.min(W-x,b.w+pad*2), rh=Math.min(H-y,b.h+pad*2);
    const out=document.createElement('canvas'); out.width=rw; out.height=rh; out.getContext('2d').drawImage(im,x,y,rw,rh,0,0,rw,rh);
    const url=out.toDataURL('image/png'), img=new Image(); img.src=url;
    state.assets.push({id:'asset_'+crypto.randomUUID(),name:`${prefix}_${String(n).padStart(2,'0')}`,url,img,w:rw,h:rh,pngDataUrl:url,sourceId:src.id,auto:true}); n++;
  }
}
function setMode(m){state.mode=m;document.body.className='mode-'+m;$('#tabCrop').classList.toggle('active',m==='crop');$('#tabCompose').classList.toggle('active',m==='compose');$('#canvasTitle').textContent=m==='crop'?'切り抜きプレビュー':'料理プレビュー';$('#hint').textContent=m==='crop'?toolHint():'素材をクリックして追加 / レイヤーをドラッグして移動';if(m==='compose') fitDish(); else fitSource();draw()}
$('#tabCrop').onclick=()=>setMode('crop');$('#tabCompose').onclick=()=>setMode('compose');
function renderSources(){const box=$('#sourceList');box.innerHTML='';state.sources.forEach(s=>{const d=document.createElement('div');d.className='src-item'+(s===state.source?' active':'');d.innerHTML=`<img class="thumb" src="${s.img.src}"><div class="meta"><b>${esc(s.name)}</b><span>${s.img.naturalWidth}×${s.img.naturalHeight}</span></div>`;d.onclick=()=>{state.source=s;state.selection=null;state.poly=[];state.free=[];renderSources();fitSource();draw()};box.appendChild(d)})}
function fitSource(){if(!state.source)return;const r=wrap.getBoundingClientRect(),im=state.source.img;const s=Math.min((r.width-30)/im.naturalWidth,(r.height-30)/im.naturalHeight);state.view.scale=s;state.view.x=(r.width-im.naturalWidth*s)/2;state.view.y=(r.height-im.naturalHeight*s)/2;updateZoomUI();draw()}
function fitDish(){const r=wrap.getBoundingClientRect();const s=Math.min((r.width-40)/state.dish.w,(r.height-40)/state.dish.h);state.view.scale=s;state.view.x=(r.width-state.dish.w*s)/2;state.view.y=(r.height-state.dish.h*s)/2;updateZoomUI();draw()}
function updateZoomUI(){const p=Math.round(state.view.scale*100);$('#zoomRange').value=Math.max(10,Math.min(500,p));$('#zoomVal').textContent=p+'%'}
function draw(){ctx.save();ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);ctx.clearRect(0,0,canvas.width/devicePixelRatio,canvas.height/devicePixelRatio);if(state.mode==='crop')drawCrop();else drawCompose();ctx.restore()}
function checker(x,y,w,h,size=16){ctx.fillStyle='#fff';ctx.fillRect(x,y,w,h);ctx.fillStyle='#e9e9e9';for(let yy=0;yy<h;yy+=size)for(let xx=0;xx<w;xx+=size)if(((xx/size+yy/size)&1)===0)ctx.fillRect(x+xx,y+yy,Math.min(size,w-xx),Math.min(size,h-yy))}
function drawCrop(){if(!state.source)return;const {img}=state.source,{scale:s,x,y}=state.view;checker(x,y,img.naturalWidth*s,img.naturalHeight*s,12);ctx.drawImage(img,x,y,img.naturalWidth*s,img.naturalHeight*s);ctx.lineWidth=2;ctx.strokeStyle='#ff552f';ctx.fillStyle='#ff552f22';if(state.selection){const p=selectionScreenPath(state.selection);ctx.save();ctx.beginPath();pathToCtx(p);ctx.fill();ctx.stroke();ctx.restore()} if(state.tool==='polygon'&&state.poly.length){ctx.beginPath();state.poly.forEach((p,i)=>{const q=imgToScreen(p);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)});ctx.stroke();for(const p of state.poly){const q=imgToScreen(p);ctx.beginPath();ctx.arc(q.x,q.y,4,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.stroke()}} if(state.tool==='free'&&state.free.length){ctx.beginPath();state.free.forEach((p,i)=>{const q=imgToScreen(p);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)});ctx.stroke()}}
function drawCompose(){const {scale:s,x,y}=state.view,w=state.dish.w,h=state.dish.h;if(state.dish.bg==='checker')checker(x,y,w*s,h*s,16);else{ctx.fillStyle=state.dish.bg==='white'?'#fff':'#292625';ctx.fillRect(x,y,w*s,h*s)}ctx.save();ctx.translate(x,y);ctx.scale(s,s);for(let i=0;i<state.layers.length;i++){const L=state.layers[i],a=assetById(L.assetId);if(!a||!L.visible)continue;ctx.save();ctx.globalAlpha=L.opacity;ctx.translate(L.x,L.y);ctx.rotate(L.rot*Math.PI/180);ctx.scale(L.flip?-L.scale:L.scale,L.scale);ctx.drawImage(a.img,-a.w/2,-a.h/2,a.w,a.h);if(i===state.selectedLayer){ctx.globalAlpha=1;ctx.strokeStyle='#ef6035';ctx.lineWidth=2/s;ctx.setLineDash([8/s,5/s]);ctx.strokeRect(-a.w/2,-a.h/2,a.w,a.h);ctx.setLineDash([])}ctx.restore()}ctx.restore()}
function screenToImg(p){return{x:(p.x-state.view.x)/state.view.scale,y:(p.y-state.view.y)/state.view.scale}}
function imgToScreen(p){return{x:state.view.x+p.x*state.view.scale,y:state.view.y+p.y*state.view.scale}}
function evtPos(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function toolHint(){return state.tool==='rect'?'ドラッグして矩形を作成':state.tool==='polygon'?'クリックで輪郭点を追加 / ダブルクリックで確定':state.tool==='free'?'ドラッグで自由に囲む':'ドラッグして表示位置を移動'}
$$('.tool').forEach(b=>b.onclick=()=>{state.tool=b.dataset.tool;$$('.tool').forEach(x=>x.classList.toggle('active',x===b));$('#hint').textContent=toolHint();state.poly=[];state.free=[];draw()});
let lastPan=null;
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);const p=evtPos(e);if(state.mode==='compose'){const q=screenToImg(p);const idx=hitLayer(q.x,q.y);if(idx>=0){state.selectedLayer=idx;state.dragLayer={sx:q.x,sy:q.y,ox:state.layers[idx].x,oy:state.layers[idx].y};renderLayers();syncLayerEditor();draw()}return}if(state.tool==='pan'){lastPan=p;return}const q=screenToImg(p);if(state.tool==='rect'){state.drawing=true;state.selection={type:'rect',x:q.x,y:q.y,w:0,h:0};}else if(state.tool==='polygon'){state.poly.push(q);draw()}else if(state.tool==='free'){state.drawing=true;state.free=[q];}});
canvas.addEventListener('pointermove',e=>{const p=evtPos(e);if(state.mode==='compose'&&state.dragLayer){const q=screenToImg(p),L=state.layers[state.selectedLayer];L.x=state.dragLayer.ox+(q.x-state.dragLayer.sx);L.y=state.dragLayer.oy+(q.y-state.dragLayer.sy);syncLayerEditor();draw();return}if(state.mode!=='crop')return;if(state.tool==='pan'&&lastPan){state.view.x+=p.x-lastPan.x;state.view.y+=p.y-lastPan.y;lastPan=p;draw();return}if(!state.drawing)return;const q=screenToImg(p);if(state.tool==='rect'){state.selection.w=q.x-state.selection.x;state.selection.h=q.y-state.selection.y;updateSelectionInfo();draw()}else if(state.tool==='free'){state.free.push(q);draw()}});
canvas.addEventListener('pointerup',e=>{if(state.mode==='compose'){state.dragLayer=null;return}lastPan=null;if(state.tool==='rect'&&state.drawing){state.drawing=false;normalizeRect();updateSelectionInfo();draw()}else if(state.tool==='free'&&state.drawing){state.drawing=false;if(state.free.length>2)state.selection={type:'poly',points:simplify(state.free,2.5)};state.free=[];updateSelectionInfo();draw()}});
canvas.addEventListener('dblclick',e=>{if(state.mode==='crop'&&state.tool==='polygon'&&state.poly.length>2){state.selection={type:'poly',points:[...state.poly]};state.poly=[];updateSelectionInfo();draw()}});
addEventListener('keydown',e=>{if(e.key==='Enter'&&state.mode==='crop'&&state.tool==='polygon'&&state.poly.length>2){state.selection={type:'poly',points:[...state.poly]};state.poly=[];updateSelectionInfo();draw()}if((e.key==='Delete'||e.key==='Backspace')&&state.mode==='compose'&&state.selectedLayer!=null&&!/INPUT|TEXTAREA/.test(document.activeElement.tagName)){deleteLayer()}})
function normalizeRect(){let r=state.selection;if(!r||r.type!=='rect')return;if(r.w<0){r.x+=r.w;r.w=-r.w}if(r.h<0){r.y+=r.h;r.h=-r.h}}
function selectionScreenPath(sel){if(sel.type==='rect'){const a=imgToScreen({x:sel.x,y:sel.y});return{type:'rect',x:a.x,y:a.y,w:sel.w*state.view.scale,h:sel.h*state.view.scale}}return{type:'poly',points:sel.points.map(imgToScreen)}}
function pathToCtx(p){if(p.type==='rect'){ctx.rect(p.x,p.y,p.w,p.h)}else{p.points.forEach((q,i)=>i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y));ctx.closePath()}}
function updateSelectionInfo(){const b=selBounds();$('#selX').textContent=b?Math.round(b.x):'-';$('#selY').textContent=b?Math.round(b.y):'-';$('#selW').textContent=b?Math.round(b.w):'-';$('#selH').textContent=b?Math.round(b.h):'-'}
function selBounds(){const s=state.selection;if(!s)return null;if(s.type==='rect')return s;const xs=s.points.map(p=>p.x),ys=s.points.map(p=>p.y);return{x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys)}}
function simplify(points,tol){if(points.length<3)return points;const out=[points[0]];let last=points[0];for(let i=1;i<points.length-1;i++){const p=points[i];if(Math.hypot(p.x-last.x,p.y-last.y)>=tol){out.push(p);last=p}}out.push(points.at(-1));return out}
$('#clearSelection').onclick=()=>{state.selection=null;state.poly=[];state.free=[];updateSelectionInfo();draw()};
$('#cropPadding').oninput=e=>$('#padVal').textContent=e.target.value+'px';$('#alphaThreshold').oninput=e=>$('#alphaVal').textContent=e.target.value;
$('#zoomRange').oninput=e=>{const old=state.view.scale,n=+e.target.value/100;const r=wrap.getBoundingClientRect(),cx=r.width/2,cy=r.height/2;state.view.x=cx-(cx-state.view.x)*n/old;state.view.y=cy-(cy-state.view.y)*n/old;state.view.scale=n;updateZoomUI();draw()};
$('#zoomIn').onclick=()=>zoomAt(1.2);$('#zoomOut').onclick=()=>zoomAt(1/1.2);function zoomAt(f){const r=wrap.getBoundingClientRect(),cx=r.width/2,cy=r.height/2,old=state.view.scale,n=Math.max(.1,Math.min(5,old*f));state.view.x=cx-(cx-state.view.x)*n/old;state.view.y=cy-(cy-state.view.y)*n/old;state.view.scale=n;updateZoomUI();draw()}
$('#fitView').onclick=()=>state.mode==='crop'?fitSource():fitDish();
$('#uploadBtn').onclick=()=>$('#uploadInput').click();$('#uploadInput').onchange=e=>loadSources(e.target.files);async function loadSources(files){for(const f of files){const url=URL.createObjectURL(f),img=await imgFrom(url);state.sources.push({id:'src_'+crypto.randomUUID(),name:f.name,file:f.name,img,url});}state.source=state.sources.at(-1);renderSources();fitSource();}
function cropCanvasFromSelection(sel=state.selection){if(!sel||!state.source)return null;const pad=+$('#cropPadding').value,b=selBoundsFor(sel),im=state.source.img;let x=Math.floor(b.x-pad),y=Math.floor(b.y-pad),w=Math.ceil(b.w+2*pad),h=Math.ceil(b.h+2*pad);x=Math.max(0,x);y=Math.max(0,y);w=Math.min(im.naturalWidth-x,w);h=Math.min(im.naturalHeight-y,h);if(w<=0||h<=0)return null;const c=document.createElement('canvas');c.width=w;c.height=h;const g=c.getContext('2d');if(sel.type==='rect'){g.drawImage(im,x,y,w,h,0,0,w,h)}else{g.save();g.translate(-x,-y);g.beginPath();sel.points.forEach((p,i)=>i?g.lineTo(p.x,p.y):g.moveTo(p.x,p.y));g.closePath();g.clip();g.drawImage(im,0,0);g.restore()}return{canvas:c,x,y,w,h}}
function selBoundsFor(s){if(s.type==='rect')return s;const xs=s.points.map(p=>p.x),ys=s.points.map(p=>p.y);return{x:Math.min(...xs),y:Math.min(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys)}}
$('#downloadCrop').onclick=()=>{const cr=cropCanvasFromSelection();if(!cr)return toast('先に切り抜き範囲を選択してください');downloadCanvas(cr.canvas,($('#assetName').value||'crop')+'.png')};
$('#registerCrop').onclick=()=>{const cr=cropCanvasFromSelection();if(!cr)return toast('切り抜き範囲を選択してください');const name=($('#assetName').value||('asset_'+(state.assets.length+1))).trim();registerCanvasAsset(cr.canvas,name);toast('素材に登録しました')};
function registerCanvasAsset(c,name){const url=c.toDataURL('image/png'),img=new Image();img.src=url;state.assets.push({id:'asset_'+crypto.randomUUID(),name,url,img,w:c.width,h:c.height,pngDataUrl:url});renderAssets()}
function renderAssets(){const box=$('#assetLibrary');box.innerHTML='';state.assets.forEach(a=>{const d=document.createElement('div');d.className='asset-card';d.innerHTML=`<img src="${a.url}"><b title="${esc(a.name)}">${esc(a.name)}</b>`;d.onclick=()=>addLayer(a.id);box.appendChild(d)})}
function addLayer(assetId){const a=assetById(assetId);if(!a)return;const L={id:'layer_'+crypto.randomUUID(),assetId,name:a.name,x:state.dish.w/2,y:state.dish.h/2,scale:Math.min(1,360/Math.max(a.w,a.h)),rot:0,opacity:1,flip:false,visible:true};state.layers.push(L);state.selectedLayer=state.layers.length-1;renderLayers();syncLayerEditor();draw();toast('レイヤーを追加しました')}
function assetById(id){return state.assets.find(a=>a.id===id)}
function renderLayers(){const box=$('#layerList');box.innerHTML='';[...state.layers].reverse().forEach((L,ri)=>{const idx=state.layers.length-1-ri,a=assetById(L.assetId),d=document.createElement('div');d.className='layer-item'+(idx===state.selectedLayer?' active':'');d.innerHTML=`<span class="layer-handle">☷</span><img class="thumb" src="${a?.url||''}"><div class="meta"><b>${esc(L.name)}</b><span>${Math.round(L.scale*100)}% / ${Math.round(L.rot)}°</span></div><div class="layer-actions"><button class="small">${L.visible?'👁':'◌'}</button></div>`;d.onclick=()=>{state.selectedLayer=idx;renderLayers();syncLayerEditor();draw()};d.querySelector('button').onclick=(e)=>{e.stopPropagation();L.visible=!L.visible;renderLayers();draw()};box.appendChild(d)});$('#layerCount').textContent=state.layers.length}
function syncLayerEditor(){const L=state.layers[state.selectedLayer];$('#layerEditor').style.opacity=L?'1':'.45';if(!L)return;$('#layerName').value=L.name;$('#layerX').value=Math.round(L.x);$('#layerY').value=Math.round(L.y);$('#layerScale').value=Math.round(L.scale*100);$('#layerRot').value=Math.round(L.rot);$('#layerOpacity').value=Math.round(L.opacity*100);$('#layerFlip').checked=L.flip;$('#layerXVal').textContent=Math.round(L.x);$('#layerYVal').textContent=Math.round(L.y);$('#layerScaleVal').textContent=Math.round(L.scale*100)+'%';$('#layerRotVal').textContent=Math.round(L.rot)+'°';$('#layerOpacityVal').textContent=Math.round(L.opacity*100)+'%'}
[['layerX','x',1],['layerY','y',1],['layerScale','scale',.01],['layerRot','rot',1],['layerOpacity','opacity',.01]].forEach(([id,k,m])=>$('#'+id).oninput=e=>{const L=state.layers[state.selectedLayer];if(!L)return;L[k]=+e.target.value*m;syncLayerEditor();renderLayers();draw()});$('#layerName').onchange=e=>{const L=state.layers[state.selectedLayer];if(L){L.name=e.target.value;renderLayers()}};$('#layerFlip').onchange=e=>{const L=state.layers[state.selectedLayer];if(L){L.flip=e.target.checked;draw()}};
$('#layerUp').onclick=()=>moveLayer(1);$('#layerDown').onclick=()=>moveLayer(-1);function moveLayer(dir){let i=state.selectedLayer;if(i==null)return;let j=Math.max(0,Math.min(state.layers.length-1,i+dir));if(i===j)return;[state.layers[i],state.layers[j]]=[state.layers[j],state.layers[i]];state.selectedLayer=j;renderLayers();draw()}
$('#delLayer').onclick=deleteLayer;function deleteLayer(){if(state.selectedLayer==null)return;state.layers.splice(state.selectedLayer,1);state.selectedLayer=Math.min(state.layers.length-1,state.selectedLayer);if(state.layers.length===0)state.selectedLayer=null;renderLayers();syncLayerEditor();draw()}
$('#dupLayer').onclick=()=>{const L=state.layers[state.selectedLayer];if(!L)return;const n={...L,id:'layer_'+crypto.randomUUID(),x:L.x+20,y:L.y+20};state.layers.push(n);state.selectedLayer=state.layers.length-1;renderLayers();syncLayerEditor();draw()}
function hitLayer(x,y){for(let i=state.layers.length-1;i>=0;i--){const L=state.layers[i],a=assetById(L.assetId);if(!L.visible||!a)continue;const dx=x-L.x,dy=y-L.y,c=Math.cos(-L.rot*Math.PI/180),s=Math.sin(-L.rot*Math.PI/180);let lx=(dx*c-dy*s)/(L.scale*(L.flip?-1:1)),ly=(dx*s+dy*c)/L.scale;if(Math.abs(lx)<=a.w/2&&Math.abs(ly)<=a.h/2)return i}return -1}
$('#dishW').onchange=e=>{state.dish.w=+e.target.value;fitDish()};$('#dishH').onchange=e=>{state.dish.h=+e.target.value;fitDish()};$('#bgMode').onchange=e=>{state.dish.bg=e.target.value;draw()};$('#resetDish').onclick=()=>{state.layers=[];state.selectedLayer=null;renderLayers();syncLayerEditor();draw()};
function renderDishToCanvas(){const c=document.createElement('canvas');c.width=state.dish.w;c.height=state.dish.h;const g=c.getContext('2d');if(state.dish.bg==='white'){g.fillStyle='#fff';g.fillRect(0,0,c.width,c.height)}else if(state.dish.bg==='dark'){g.fillStyle='#292625';g.fillRect(0,0,c.width,c.height)}for(const L of state.layers){const a=assetById(L.assetId);if(!a||!L.visible)continue;g.save();g.globalAlpha=L.opacity;g.translate(L.x,L.y);g.rotate(L.rot*Math.PI/180);g.scale(L.flip?-L.scale:L.scale,L.scale);g.drawImage(a.img,-a.w/2,-a.h/2,a.w,a.h);g.restore()}return c}
$('#exportPng').onclick=()=>downloadCanvas(renderDishToCanvas(),($('#recipeName').value||'dish_preview')+'.png');
$('#saveRecipe').onclick=()=>{const name=($('#recipeName').value||'').trim();if(!name)return toast('パターン名を入力してください');state.recipes[name]={name,dish:{...state.dish},layers:state.layers.map(L=>({...L}))};renderRecipes();toast('パターンを保存しました')};
function renderRecipes(){const s=$('#recipeList'),cur=s.value;s.innerHTML='<option value="">保存済みパターン...</option>';for(const name of Object.keys(state.recipes)){const o=document.createElement('option');o.value=name;o.textContent=name;s.appendChild(o)}s.value=cur}
$('#recipeList').onchange=e=>{const r=state.recipes[e.target.value];if(!r)return;state.dish={...r.dish};state.layers=r.layers.map(L=>({...L}));state.selectedLayer=state.layers.length?state.layers.length-1:null;$('#dishW').value=state.dish.w;$('#dishH').value=state.dish.h;$('#bgMode').value=state.dish.bg;renderLayers();syncLayerEditor();fitDish();draw()};
$('#assetUploadBtn').onclick=()=>$('#assetUpload').click();$('#assetUpload').onchange=e=>loadAssetFiles(e.target.files);const drop=$('#assetDrop');['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.ondrop=e=>loadAssetFiles(e.dataTransfer.files);async function loadAssetFiles(files){for(const f of files){const url=URL.createObjectURL(f),img=await imgFrom(url);state.assets.push({id:'asset_'+crypto.randomUUID(),name:f.name.replace(/\.[^.]+$/,''),url,img,w:img.naturalWidth,h:img.naturalHeight,file:f})}renderAssets();toast(files.length+'個の素材を追加')}
function autoDetectComponents(){if(!state.source)return;status('自動分割中...');const im=state.source.img,c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(im,0,0);const dat=g.getImageData(0,0,c.width,c.height).data,W=c.width,H=c.height,thr=+$('#alphaThreshold').value;const ds=3,w=Math.ceil(W/ds),h=Math.ceil(H/ds),mask=new Uint8Array(w*h);for(let yy=0;yy<h;yy++)for(let xx=0;xx<w;xx++){let a=0;for(let sy=0;sy<ds;sy++)for(let sx=0;sx<ds;sx++){const x=Math.min(W-1,xx*ds+sx),y=Math.min(H-1,yy*ds+sy);a=Math.max(a,dat[(y*W+x)*4+3])}if(a>thr)mask[yy*w+xx]=1}const seen=new Uint8Array(w*h),comps=[];const qx=new Int32Array(w*h),qy=new Int32Array(w*h);for(let yy=0;yy<h;yy++)for(let xx=0;xx<w;xx++){let idx=yy*w+xx;if(!mask[idx]||seen[idx])continue;let qs=0,qe=0;qx[qe]=xx;qy[qe++]=yy;seen[idx]=1;let minx=xx,maxx=xx,miny=yy,maxy=yy,count=0;while(qs<qe){const x=qx[qs],y=qy[qs++];count++;minx=Math.min(minx,x);maxx=Math.max(maxx,x);miny=Math.min(miny,y);maxy=Math.max(maxy,y);const ns=[[x+1,y],[x-1,y],[x,y+1],[x,y-1]];for(const [nx,ny] of ns){if(nx<0||ny<0||nx>=w||ny>=h)continue;const ni=ny*w+nx;if(mask[ni]&&!seen[ni]){seen[ni]=1;qx[qe]=nx;qy[qe++]=ny}}}if(count>40)comps.push({x:minx*ds,y:miny*ds,w:(maxx-minx+1)*ds,h:(maxy-miny+1)*ds,count})}comps.sort((a,b)=>b.count-a.count);state.detected=comps.slice(0,60);renderDetected();status('自動分割完了: '+state.detected.length+'候補')}
$('#autoDetect').onclick=autoDetectComponents;function renderDetected(){const box=$('#detectedList');box.innerHTML='';state.detected.forEach((b,i)=>{const c=document.createElement('canvas');c.width=b.w;c.height=b.h;c.getContext('2d').drawImage(state.source.img,b.x,b.y,b.w,b.h,0,0,b.w,b.h);const d=document.createElement('div');d.className='asset-card';d.innerHTML=`<img src="${c.toDataURL()}"><b>候補 ${i+1}</b>`;d.onclick=()=>{state.selection={type:'rect',x:b.x,y:b.y,w:b.w,h:b.h};$('#assetName').value='asset_'+(i+1);updateSelectionInfo();draw()};box.appendChild(d)})}
$('#trimAlpha').onclick=()=>{const cr=cropCanvasFromSelection();if(!cr)return;const g=cr.canvas.getContext('2d',{willReadFrequently:true}),id=g.getImageData(0,0,cr.w,cr.h),thr=+$('#alphaThreshold').value;let minx=cr.w,miny=cr.h,maxx=-1,maxy=-1;for(let y=0;y<cr.h;y++)for(let x=0;x<cr.w;x++)if(id.data[(y*cr.w+x)*4+3]>thr){minx=Math.min(minx,x);miny=Math.min(miny,y);maxx=Math.max(maxx,x);maxy=Math.max(maxy,y)}if(maxx<0)return;state.selection={type:'rect',x:cr.x+minx,y:cr.y+miny,w:maxx-minx+1,h:maxy-miny+1};updateSelectionInfo();draw()};
$('#invertMask').onclick=()=>toast('反転マスクは現在の版ではPNG書き出し時のみ対応予定');
function serializeProject(){return{version:state.projectVersion,dish:state.dish,assets:state.assets.map(a=>({id:a.id,name:a.name,w:a.w,h:a.h,pngDataUrl:a.pngDataUrl||null,url:a.pngDataUrl||null})).filter(a=>a.pngDataUrl),layers:state.layers,recipes:state.recipes}}
$('#saveProject').onclick=()=>downloadBlob(new Blob([JSON.stringify(serializeProject(),null,2)],{type:'application/json'}),'kani_asset_project.json');$('#loadProjectBtn').onclick=()=>$('#loadProject').click();$('#loadProject').onchange=async e=>{const data=JSON.parse(await e.target.files[0].text());state.dish=data.dish||state.dish;state.assets=[];for(const a of data.assets||[]){const img=await imgFrom(a.pngDataUrl||a.url);state.assets.push({...a,img,url:a.pngDataUrl||a.url,pngDataUrl:a.pngDataUrl||a.url})}state.layers=data.layers||[];state.recipes=data.recipes||{};state.selectedLayer=state.layers.length?state.layers.length-1:null;renderAssets();renderLayers();renderRecipes();syncLayerEditor();setMode('compose');toast('プロジェクトを読み込みました')};
$('#exportGame').onclick=async()=>{status('ZIPを作成中...');const entries=[];const manifest={format:'kani-dish-assets-v1',canvas:{width:state.dish.w,height:state.dish.h},assets:[],recipes:state.recipes};for(const a of state.assets){let blob;if(a.file)blob=a.file;else if(a.pngDataUrl)blob=dataUrlToBlob(a.pngDataUrl);else continue;const fn=safe(a.name)+'.png';entries.push({name:'assets/'+fn,data:new Uint8Array(await blob.arrayBuffer())});manifest.assets.push({id:a.id,name:a.name,file:'assets/'+fn,width:a.w,height:a.h})}entries.push({name:'dish_assets.json',data:new TextEncoder().encode(JSON.stringify(manifest,null,2))});entries.push({name:'README.txt',data:new TextEncoder().encode('dish_assets.json と assets/ をゲームへコピーしてください。recipes 内の layers は x/y/scale/rot/opacity/flip と assetId を保持しています。\n')});const zip=makeZip(entries);downloadBlob(new Blob([zip],{type:'application/zip'}),'kani_game_assets.zip');status('ゲーム用ZIPを書き出しました');toast('ゲーム用ZIPを保存しました')};
function makeZip(entries){const parts=[],central=[];let offset=0;for(const e of entries){const name=new TextEncoder().encode(e.name),data=e.data,crc=crc32(data);const local=new Uint8Array(30+name.length+data.length),v=new DataView(local.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0,true);v.setUint16(8,0,true);v.setUint16(10,0,true);v.setUint16(12,0,true);v.setUint32(14,crc,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,name.length,true);v.setUint16(28,0,true);local.set(name,30);local.set(data,30+name.length);parts.push(local);const cen=new Uint8Array(46+name.length),c=new DataView(cen.buffer);c.setUint32(0,0x02014b50,true);c.setUint16(4,20,true);c.setUint16(6,20,true);c.setUint16(8,0,true);c.setUint16(10,0,true);c.setUint16(12,0,true);c.setUint16(14,0,true);c.setUint32(16,crc,true);c.setUint32(20,data.length,true);c.setUint32(24,data.length,true);c.setUint16(28,name.length,true);c.setUint16(30,0,true);c.setUint16(32,0,true);c.setUint16(34,0,true);c.setUint16(36,0,true);c.setUint32(38,0,true);c.setUint32(42,offset,true);cen.set(name,46);central.push(cen);offset+=local.length}const centralSize=central.reduce((n,a)=>n+a.length,0),end=new Uint8Array(22),d=new DataView(end.buffer);d.setUint32(0,0x06054b50,true);d.setUint16(4,0,true);d.setUint16(6,0,true);d.setUint16(8,entries.length,true);d.setUint16(10,entries.length,true);d.setUint32(12,centralSize,true);d.setUint32(16,offset,true);d.setUint16(20,0,true);return concat([...parts,...central,end])}
const crcTable=(()=>{const t=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;t[n]=c>>>0}return t})();function crc32(arr){let c=0xffffffff;for(const b of arr)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}function concat(arrs){const n=arrs.reduce((s,a)=>s+a.length,0),out=new Uint8Array(n);let o=0;for(const a of arrs){out.set(a,o);o+=a.length}return out}
function downloadCanvas(c,name){c.toBlob(b=>downloadBlob(b,name),'image/png')}function downloadBlob(b,name){const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000)}function dataUrlToBlob(u){const [h,d]=u.split(','),m=h.match(/:(.*?);/)[1],bin=atob(d),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return new Blob([a],{type:m})}function safe(s){return s.replace(/[^a-zA-Z0-9_-]+/g,'_').replace(/^_+|_+$/g,'')||'asset'}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
resize();init();
})();
